In [2]:
import pandas as pd

In [3]:
# pip install pandas

In [4]:
revenue =   pd.Series([5200,599,6000,1000,4000, 8000]) # one dimensional array 
print(revenue)

0    5200
1     599
2    6000
3    1000
4    4000
5    8000
dtype: int64

In [5]:
revenue =   pd.Series([5200,599,6000,1000,4000],
                    index=["Jan", "Feb", "Mar", "Apr", "May"]) # one dimensional array 
print(revenue)
print(revenue['Feb'])

Jan    5200
Feb     599
Mar    6000
Apr    1000
May    4000
dtype: int64
599

In [6]:
data = {
    "name":       ["Alice", "Bob", "Carol", "David", "Eve"],
    "department": ["Engineering", "Finance", "Engineering", "HR", "Finance"],
    "salary":     [85000, 72000, 91000, 65000, 78000],
    "active":     [True, True, False, True, True]
}

df = pd.DataFrame(data)
print(df)

    name   department  salary  active
0  Alice  Engineering   85000    True
1    Bob      Finance   72000    True
2  Carol  Engineering   91000   False
3  David           HR   65000    True
4    Eve      Finance   78000    True

In [8]:
# csv
df = pd.read_csv('employees_data.csv')

In [28]:
# data hai kitna bara ? what's size of data 
# data type kiya hian ?
# statistics (mean, median, mode) 
# Aggreated values (max, min, avg)

In [ ]:
# Metadata - data of data

In [12]:
print(df.shape) # rows, cloumns
print(df.dtypes)
print(df.columns)

(5, 4)
name           object
department     object
salary        float64
active         object
dtype: object
Index(['name', 'department', 'salary', 'active'], dtype='object')

In [13]:
df.head(2)  # by default returns first 5 rows

    name department  salary active
0   Ayan        ENG  2000.0    yes
1  Nasir        FIN  5000.0    yes

In [31]:
df.tail(2)  # by default returns last  5 rows

    name department  salary active
3  Irfan         DA  9000.0     no
4   ayaz         DA     NaN     no

In [14]:
df.info()                # column names, non-null counts, dtypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        5 non-null      object
 1   department  5 non-null      object
 2   salary      3 non-null      float64
 3   active      5 non-null      object
dtypes: float64(1), object(3)
memory usage: 292.0+ bytes

In [15]:
df.describe()            # statistics for numeric columns

       salary
count     3.0
mean   5000.0
std    3000.0
min    2000.0
25%    3500.0
50%    5000.0
75%    6500.0
max    8000.0